### ISSUE TITLE
Superstream source error 

### ISSUE THREAD

**Issue by Chickenshrimps** [almightyhak/aniyomi-extensions#101]
### Source information

Superstream 14.11

### Source language

English 

### Steps to reproduce

Open Superstream source
Click on Web view
Source page error shows 
![Screenshot_2024_0804_100636](https://github.com/user-attachments/assets/451daf3c-9535-48bc-83e6-398f31f2b0ec)

### Expected behavior

It should open quickly 

### Actual behavior

Blank white screen with page server error

### Aniyomi version

Stable 0.16.4.3

### Android version

Android 12

### Other details

Pls fix it ASAP 🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
dude you don't need to make so many issues. closed in favor of #103

**Comment by Chickenshrimps** [comment]
> dude you don't need to make so many issues. closed in favor of #103

Aren't you going to change it? Closed as in not planned? 
Pls try to update it or at least add a new extensions source fixing the broken link 
I am making so many issues because that source is important to me
