### ISSUE TITLE
Superstream source url change 

### ISSUE THREAD

**Issue by Chickenshrimps** [almightyhak/aniyomi-extensions#102]
### Source information

Superstream 14.11

### Source language

English 

### Source new URL

https://www.movieboxpro.app/

### Other details

Pls update 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
again you don't need to make so many issues. closed in favor of #103
