### ISSUE TITLE
Anime episodes not loading (Aniwave)

### ISSUE THREAD

**Issue by JudgeDreddpool** [almightyhak/aniyomi-extensions#11]
### Source information

Aniwave 14.69

### Source language

English

### Steps to reproduce

1. Open any anime through the Aniwave extension
2. Select any episode to play
3. Get greeted by the following error
![Screenshot_20240629-012110_Aniyomi](https://github.com/almightyhak/aniyomi-extensions/assets/51933874/9e640f6a-98c1-46bc-9ab7-13c0dfe0812d)

### Expected behavior

Should play the anime episode normally.

### Actual behavior

"loading failed: https: HTTP error 404 Not Found" message keeps popping up

### Aniyomi version

Preview r7567

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
temporary issue just leave it be it'll fix itself
