### ISSUE TITLE
Add Anix as a Source or Domain Selection Option in Aniwave Extension

### ISSUE THREAD

**Issue by YouSummoner** [almightyhak/aniyomi-extensions#113]
### Source name

Anix

### Source link

Anix.to

### Source language

English

### Other details

I would like to request the addition of Anix as a source or, if possible, as a alternate domain in the Aniwave extension. Both Anix and Aniwave use the same video backend but have different user interfaces. Given that Aniwave frequently gets blocked while Anix consistently works, adding Anix would be a good option.
Anix also has multiple domains all listed at anix.me and  a anixtv.to domain as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/almightyhak/aniyomi-extensions) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
closed in favor of #95
