### ISSUE TITLE
AnimePahe extension not showing in Aniyomi after r7646 update

### ISSUE THREAD

**Issue by YouSummoner** [almightyhak/aniyomi-extensions#20]
### Source information

AnimePahe 14.27

### Source language

English 

### Steps to reproduce

1. Update Aniyomi to Preview r7646.
2. Install the AnimePahe extension if not already installed.
3. Go to the installed extensions list and look for AnimePahe.

### Expected behavior

The extension should be available after installing.

### Actual behavior

The extension doesn't show up in Aniyomi whatsoever.

### Aniyomi version

Preview r7646

### Android version

Android 14

### Other details

It just disappeared after updating Aniyomi to the latest Preview version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Isn't r7567 the lastest version?

**Comment by YouSummoner** [comment]
Yes, looks like they deleted the r7646 update. I updated in the brief time
it was available and and noticed this issue... I'll downgrade for now...

**Comment by YouSummoner** [comment]
Nope, it isn't fixed, I'm having the same issue with the latest
stable(v0.16.4.0) and latest preview(r7649) of Aniyomi.
After tapping "Trust" on the extension when it appears in the extension
list, it just disappears and doesn't even show up anymore.

**Comment by almightyhak** [comment]
Have you looked at your extension filter?

**Comment by YouSummoner** [comment]
Yes, nothing is disabled in there, but it just disappeared on its own after
the Aniyomi update

**Comment by almightyhak** [comment]
Is this only happening with AnimePahe?

**Comment by YouSummoner** [comment]
Alright, this is fixed with Aniyomi 0.16.4.3 and Preview r7654...
