### ISSUE TITLE
AsianLoad: Domain Changed

### ISSUE THREAD

**Issue by Pjppy2** [almightyhak/aniyomi-extensions#37]
### Source information

Asianload 14.38

### Source language

English

### Source new URL

https://draplay.info/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Fixed
