### ISSUE TITLE
Aniwave Throwing Error

### ISSUE THREAD

**Issue by YouSummoner** [almightyhak/aniyomi-extensions#58]
### Source information

Aniwave 14.69

### Source language

English 

### Steps to reproduce

Go to any entry from aniwave and try to refresh or load episodes.

### Expected behavior

All episodes should load.

### Actual behavior

It gives an error.
![Screenshot_20240716-213934_Aniyomi](https://github.com/user-attachments/assets/e771c50a-d042-4c56-9275-dd4b0a356646)

### Aniyomi version

Preview r7798

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] #60
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
"I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue." 🤦 Please actually read the acknowledgments instead of 
blindly checking them. Closed in favor of #56
