### ISSUE TITLE
FMovies Extension Down Due to URL Change

### ISSUE THREAD

**Issue by Alexxiconify** [almightyhak/aniyomi-extensions#61]
### Source information

FMovies 14.25 (English)

### Source language

English

### Steps to reproduce

1. Open any video OR open the FMovies extension
2.And it shows no results found
3. When I open in Web View it doesn't connect.

### Expected behavior

The videos should be findable and playable.

### Actual behavior

The site is down I checked and it was fmovies24.to (what extension currently has it as). but they moved to fmovies.co (www4.fmovies.co to be exact), the site being down it won't allow me to view or find videos.

### Aniyomi version

0.16.4.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Please use the proper issue template
