### ISSUE TITLE
FMovies changed their website. The one on Aniyomi is outdated.

### ISSUE THREAD

**Issue by Shikamaru30** [almightyhak/aniyomi-extensions#65]
### Source information

FMovies - 14.25

### Source language

Engish

### Steps to reproduce

Clicking on FMovies webview ends up with indefinite loading.

It's because they changed their website, as many others in the subreddit noticed.

### Expected behavior

Should show the site and all the movies.

### Actual behavior

Doesn't show the site and all the movies.

### Aniyomi version

Latest version

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by almightyhak** [comment]
Wrong template

**Comment by Shikamaru30** [comment]
> Wrong template 

Ok. But are you going to address the existing issue or...?

**Comment by almightyhak** [comment]
Eventually
