### ISSUE TITLE
Neko-Sama nethttps error

### ISSUE THREAD

**Issue by Lameur** [almightyhak/aniyomi-extensions#72]
### Source information

Neko-Sama 14.11

### Source language

Français

### Steps to reproduce

Cherche for an anime like Owarimonogatari with Neko-Sama and you get this ![Screenshot_20240722_232850_Aniyomi](https://github.com/user-attachments/assets/65002afd-e2e5-481a-ad7c-5801d8439e25)

### Expected behavior

Anime page to be successful.

### Actual behavior

Unable to resolve "neko-sama.nethttps"

### Aniyomi version

App version: 0.16.4.3 (standard, 959f84a, 124, 2024-07-01T22:25Z) Android version: 14 (SDK 34; build UP1A.231005.007.A346BXXU7CXE1) Android build ID: UP1A.231005.007.A346BXXU7CXE1 Device brand: samsung Device manufacturer: samsung Device name: a34x (a34xeea) Device model: SM-A346B WebView: Android System WebView Dev 128.0.6601.2 MPV version: 4d32db2 Libplacebo version: v7.349.0 FFmpeg version: n7.0

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by Lameur** [comment]
Ah, and I have forgotten to say that the recent section don't work but the popular section work... 🤷‍♂️

**Comment by mobby45** [comment]
Issue resolved !
