### ISSUE TITLE
Source Request: Zoro / Zoroxtv

### ISSUE THREAD

**Issue by shadow-nocnir** [almightyhak/aniyomi-extensions#75]
### Source name

Zoro

### Source link

https://zoroxtv.to/

### Source language

English

### Other details

There is an extension in the repository with a file name of `zoro`, but its extension name is HiAnime. This is another website, but uses the same zoro theme, I think.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/almightyhak/aniyomi-extensions) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by LAST-pie** [comment]
It was the relan zoro previously. Item recently change ip address to aniwatch.to then again to hianime.to
The zoro you're saying is just a copy of the original
