### ISSUE TITLE
Aniwave extension not working

### ISSUE THREAD

**Issue by LAST-pie** [almightyhak/aniyomi-extensions#77]
### Source information

Aniwave 14.69 

### Source language

English 

### Steps to reproduce

1. First step; open aniwave extension
2. Second: open any anime series
3. Issue : it reloads for a sec then it shows - 
![Screenshot_20240726-153646_Kuukiyomi](https://github.com/user-attachments/assets/09b95cfd-047e-4503-9f9a-8f00852617ee)

### Expected behavior

Should show all listed episodes 

### Actual behavior

![Screenshot_20240726-153646_Kuukiyomi](https://github.com/user-attachments/assets/7f5bb003-1a07-4b8f-90c4-e015a4cf0b7b)

### Aniyomi version

I'm using a fork of aniyomi (eg. Kuukiyomi v0. 3.2) 

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kinoarizu** [comment]
I have the same issue :(

For now i am using [KickAssAnime](https://kickassanime.mx) extension as the alternative.
