### ISSUE TITLE
Source request aniplay

### ISSUE THREAD

**Issue by Sage-pain** [almightyhak/aniyomi-extensions#95]
### Source name

Aniplay

### Source link

https://aniplaynow.live/

### Source language

English

### Other details

As aniwave is always breaking I request that the site aniplaynow.live (aniplaylive) be created as an extension to replace aniwave extension. I request that the feature of the aniwave extension that show if the ep is still subbed or has been dubbed be added to it example pic below.

![Screenshot_20240802-013406](https://github.com/user-attachments/assets/cc1497df-95a0-4856-a05f-0f82b6ca2ea6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/almightyhak/aniyomi-extensions) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by Curiousnewbie** [comment]
Instead of replacing aniway its better tag this one as another source request

**Comment by JosefFStraka** [comment]
Im looking into this one. Seems doable but I didnt research about video extractor they are using.

**Comment by Sage-pain** [comment]
> Instead of replacing aniwayve its better to tag this one as another source request

Almightyhak already changed the title so yea it's a source request now
